### ISSUE TITLE
Example code not running on device

### ISSUE THREAD

**Issue by rl802** [googlecodelabs/activity_transitionapi-codelab#11]
The sample app is not running on any of the Android 10 devices we tested on despite following the tutorial fully. Perhaps some permissions have changed?

**Comment by codingjeremy** [comment]
I was able to run on Android 10, can you give more details? You couldn't launch the activity and it crashed or it wouldn't work?

Please send over physical device you are using too.

Also, I fixed issue #9 , and I think that might be the issue you were having? Have a look at the code since I fixed it and let me know if that doesn't resolve it.

I'm closing, but please reopen if that doesn't resolve things for you or I misunderstood. Thanks!
